# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fec85b0afce8de259f31725ee0012e33f229a71f3f1601d2bf8c64035781ca22682f17d0b26c8a2ddd62f4dd4d43fad198d0b42b781349befd17b5b8f2f3a83f

test:
  secret_key_base: 875d9726d883ccfe67d2b32bfa767c025e1a1242ee4e50c904eefd6240a0e56ea062630c2f16e1906c20a2478182721c2194b515b3c2b70e4f5c9b272e5d74e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
